# These are config values that users can set from the GUI or the commandline
options:
  db-name:
    type: string
    default: drupal8
    description: Database name to create for supporting the Drupal 8 website

